Decouple MessageChannel check
GoogleChromeLabs/scheduler-polyfill pull request #6
Opened 2023-08-03 16:19 UTC by dlebedynskyi

Fixes https://github.com/GoogleChromeLabs/scheduler-polyfill/issues/5

Changes: 
* allow React Native to use background task, if `requestIdleCallback` is available
* separate check for delay and MessageChannel
* keep setTimeout as general fallback

2023-08-08 22:01 UTC, shaseley requested changes
Thanks for the patch! Sorry for the lag - looks good, a few nits.

2023-08-08 22:01 UTC, shaseley commented on test/test.hostcallback.js
> +          typeof requestIdleCallback === 'function';
Looks like some unrelated formatting changes snuck in, here and elsewhere - is it possible to remove those? This one in particular would be less readable IMO.

2023-08-08 22:01 UTC, shaseley commented on src/host-callback.js
> +    this.handle_ = setTimeout(() => {
nit/optional: It might be cleaner to set `this.callbackType_` above, and then set `this.handle_` once that's sorted? That would remove the duplication here and might simplify this.

2023-08-08 22:01 UTC, shaseley commented on src/host-callback.js
> +
nit: remove empty line.

2023-08-08 22:01 UTC, shaseley commented on test/test.hostcallback.js
> +      it(`should use Message channel when avaliable for "${priority}"`,
I think the test description should differ from above?

2023-08-14 18:51 UTC, dlebedynskyi commented on src/host-callback.js
> +    this.handle_ = setTimeout(() => {
I've tried to keep logic order close to original. Should be able to update.

2023-08-19 17:23 UTC, dlebedynskyi commented on test/test.hostcallback.js
> +          typeof requestIdleCallback === 'function';
I don't see this on my side. Looks like is formatting issue with linter you have + git diff. 
code itself is 
```js 
it('should return true for background tasks if requestIdleCallback exists',
        function() {
          const hasRequestIdleCallback =
            typeof requestIdleCallback === 'function';
          const hostCallback = new HostCallback(() => { }, 'background');
          expect(hostCallback.isIdleCallback()).to.equal(
              hasRequestIdleCallback);
        });

```

no extra `typeof`. 

General comment - auto formatter, like prettier,  would be great here.

2023-08-22 20:14 UTC, shaseley approved these changes

2023-08-22 20:14 UTC, shaseley commented on src/host-callback.js
> +    this.handle_ = setTimeout(() => {
No worries, this works; I might refactor at some point, but this is fine.

`requestIdleCallback` `timeout` isn't a delay though, it's a timeout that raises the priority of the callback if it hasn't run before `timeout`. We don't have the equivalent for `postTask()` (and it's not clear if we want it).

2023-08-22 20:15 UTC, shaseley commented on test/test.hostcallback.js
> +          typeof requestIdleCallback === 'function';
I pushed a small patch to fix to correct - just want to keep the blame clean. I'll get around to adding prettier at some point :).

2023-08-22 20:18 UTC, merged